name: run a0323
on:
    push: 
    schedule:
    - cron: "0 0 * * *"    
jobs:
  builds:
    name: run python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run python
      run:  
        python3 a0323.py